### ISSUE TITLE
Cancelling action should produce exit status

### ISSUE THREAD

**Issue by Darukutsu** [orhun/menyoki#51]
**Is your feature request related to a problem? Please describe.**
Throw `exit status 1` when cancelling action(pressing Esc) to be able to use in scripts.

Example usage (this is bind to key e.g.  `PrtScr`):
```
menyoki capture --root --select png && notify-send 'Screenshot taken`
```
Let's say I have decided to cancel operation, but notification will play always.

My usage:
```
menyoki -q capture --root --select png save "-" | tee "screenshot.png" | xclip -selection clipboard -t image/png && notify-send 'Screenshot taken`
```
If cancelled, this will create empty file + notification.

**Describe the solution you'd like**
Throw error/exit status by default or give option to throw it like `--error`.

**Additional context**
https://github.com/orhun/menyoki/issues/21 https://github.com/orhun/menyoki/issues/3

**Comment by orhun** [comment]
Hey, thanks for reporting!

This is now fixed in 3ecc33d92a4ad0a80549664e9e6cd9f57c635473

Can you build from source and test it out? I need to update the dependencies for the new release (and there are a lot) so I don't know when that will happen.

**Comment by Darukutsu** [comment]
<details>
  <summary>I'm not sure how long suppose rust program to compile. I stopped it manually.</summary>

```
 $  git clone https://aur.archlinux.org/menyoki-git.git&& cd menyoki-git&& makepkg -si
Cloning into 'menyoki-git'...
remote: Enumerating objects: 108, done.
remote: Counting objects: 100% (108/108), done.
remote: Compressing objects: 100% (76/76), done.
remote: Total 108 (delta 33), reused 107 (delta 32), pack-reused 0
Receiving objects: 100% (108/108), 17.48 KiB | 941.00 KiB/s, done.
Resolving deltas: 100% (33/33), done.
==> Making package: menyoki-git 1.7.0.r0.gf8b4ebe-1 (Wed 24 Jan 2024 08:12:49 PM CET)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Cloning menyoki git repo...
Cloning into bare repository '/home/daru/menyoki-git/menyoki'...
remote: Enumerating objects: 9624, done.
remote: Counting objects: 100% (1261/1261), done.
remote: Compressing objects: 100% (441/441), done.
remote: Total 9624 (delta 809), reused 1252 (delta 806), pack-reused 8363
Receiving objects: 100% (9624/9624), 1.56 MiB | 2.22 MiB/s, done.
Resolving deltas: 100% (6320/6320), done.
==> Validating source files with sha512sums...
    menyoki ... Skipped
==> Extracting sources...
  -> Creating working copy of menyoki git repo...
Cloning into 'menyoki'...
done.
==> Starting prepare()...
    Updating crates.io index
  Downloaded io-lifetimes v1.0.5
  Downloaded threadpool v1.8.1
  Downloaded hex v0.4.3
  Downloaded loop9 v0.1.3
  Downloaded iana-time-zone v0.1.53
  Downloaded pretty_assertions v1.3.0
  Downloaded mutate_once v0.1.1
  Downloaded futures-core v0.3.26
  Downloaded noisy_float v0.2.0
  Downloaded rust-ini v0.18.0
  Downloaded dlv-list v0.3.0
  Downloaded ordered-multimap v0.4.3
  Downloaded yansi v0.5.1
  Downloaded console v0.15.5
  Downloaded bytesize v1.2.0
  Downloaded shellexpand v3.1.0
  Downloaded tempfile v3.4.0
  Downloaded proc-macro2 v1.0.51
  Downloaded quick-error v2.0.1
  Downloaded x11 v2.21.0
  Downloaded rayon-core v1.10.2
  Downloaded crossbeam-channel v0.5.7
  Downloaded imgref v1.9.4
  Downloaded rayon v1.6.1
  Downloaded rustix v0.36.8
  Downloaded chrono v0.4.23
  Downloaded futures-sink v0.3.26
  Downloaded simd-adler32 v0.3.4
  Downloaded ctrlc v3.2.5
  Downloaded resize v0.7.4
  Downloaded gif-dispose v4.0.0
  Downloaded device_query v1.1.2
  Downloaded imagequant v4.1.0
  Downloaded gifski v1.10.0
  Downloaded kamadak-exif v0.5.5
  Downloaded lodepng v3.7.2
  Downloaded fallible_collections v0.4.6
  Downloaded zune-inflate v0.2.50
  Downloaded fern_colored v0.6.1
  Downloaded exr v1.5.3
  Downloaded webp v0.2.2
  Downloaded dominant_color v0.3.0
  Downloaded libwebp-sys v0.4.2
  Downloaded 43 crates (9.3 MB) in 4.41s (largest was `libwebp-sys` at 5.1 MB)
==> Starting pkgver()...
==> Updated version: menyoki-git 1.7.0.r7.g3ecc33d-1
==> Starting build()...
   Compiling libc v0.2.139
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling scopeguard v1.1.0
   Compiling crossbeam-utils v0.8.15
   Compiling proc-macro2 v1.0.51
   Compiling unicode-ident v1.0.6
   Compiling quote v1.0.23
   Compiling version_check v0.9.4
   Compiling syn v1.0.109
   Compiling once_cell v1.17.1
   Compiling rayon-core v1.10.2
   Compiling memoffset v0.8.0
   Compiling crossbeam-epoch v0.9.14
   Compiling num-traits v0.2.15
   Compiling ahash v0.7.6
   Compiling lock_api v0.4.9
   Compiling crc32fast v1.3.2
   Compiling adler v1.0.2
   Compiling bytemuck v1.13.1
   Compiling bitflags v1.3.2
   Compiling crossbeam-channel v0.5.7
   Compiling crossbeam-deque v0.8.3
   Compiling miniz_oxide v0.6.2
   Compiling rgb v0.8.36
   Compiling getrandom v0.2.8
   Compiling num_cpus v1.15.0
   Compiling log v0.4.17
   Compiling jobserver v0.1.26
   Compiling weezl v0.1.7
   Compiling either v1.8.1
   Compiling hashbrown v0.12.3
   Compiling cc v1.0.79
   Compiling flate2 v1.0.25
   Compiling rayon v1.6.1
   Compiling num-integer v0.1.45
   Compiling futures-core v0.3.26
   Compiling pkg-config v0.3.26
   Compiling color_quant v1.1.0
   Compiling smallvec v1.10.0
   Compiling lazy_static v1.4.0
   Compiling signal-hook v0.3.15
   Compiling make-cmd v0.1.0
   Compiling io-lifetimes v1.0.5
   Compiling parking_lot_core v0.9.7
   Compiling sixel-sys v0.3.1
   Compiling libwebp-sys v0.4.2
   Compiling nanorand v0.7.0
   Compiling signal-hook-registry v1.4.1
   Compiling spin v0.9.8
   Compiling num-rational v0.4.1
   Compiling futures-sink v0.3.26
   Compiling rustix v0.36.8
   Compiling simd-adler32 v0.3.4
   Compiling zune-inflate v0.2.50
   Compiling x11 v2.21.0
   Compiling mio v0.8.6
   Compiling fallible_collections v0.4.6
   Compiling threadpool v1.8.1
   Compiling atty v0.2.14
   Compiling imgref v1.9.4
   Compiling linux-raw-sys v0.1.4
   Compiling bit_field v0.10.2
   Compiling lebe v0.5.2
   Compiling jpeg-decoder v0.3.0
   Compiling half v2.2.1
   Compiling signal-hook-mio v0.2.3
   Compiling parking_lot v0.12.1
   Compiling device_query v1.1.2
   Compiling gif v0.12.0
   Compiling gif v0.11.4
   Compiling pin-project-internal v1.0.12
   Compiling tiff v0.8.1
   Compiling png v0.17.7
   Compiling noisy_float v0.2.0
   Compiling dirs-sys v0.3.7
   Compiling term_size v0.3.2
   Compiling thread_local v1.1.7
   Compiling unicode-width v0.1.10
   Compiling dlv-list v0.3.0
   Compiling fastrand v1.9.0
   Compiling scoped_threadpool v0.1.9
   Compiling pin-project v1.0.12
   Compiling arrayvec v0.7.2
   Compiling flume v0.10.14
   Compiling thiserror v1.0.38
   Compiling byteorder v1.4.3
   Compiling static_assertions v1.1.0
   Compiling nix v0.26.2
   Compiling exr v1.5.3
   Compiling imagequant v4.1.0
   Compiling tempfile v3.4.0
   Compiling ordered-multimap v0.4.3
   Compiling textwrap v0.11.0
   Compiling dirs v4.0.0
   Compiling gif-dispose v4.0.0
   Compiling thiserror-impl v1.0.38
   Compiling crossterm v0.25.0
   Compiling loop9 v0.1.3
   Compiling colored v2.0.0
   Compiling resize v0.7.4
   Compiling lodepng v3.7.2
   Compiling console v0.15.5
   Compiling ansi_colours v1.2.1
   Compiling time v0.1.45
   Compiling termcolor v1.2.0
   Compiling quick-error v2.0.1
   Compiling mutate_once v0.1.1
   Compiling iana-time-zone v0.1.53
   Compiling ansi_term v0.12.1
   Compiling strsim v0.8.0
   Compiling base64 v0.13.1
   Compiling clap v2.34.0
   Compiling chrono v0.4.23
   Compiling kamadak-exif v0.5.5
   Compiling fern_colored v0.6.1
   Compiling ctrlc v3.2.5
   Compiling shellexpand v3.1.0
   Compiling rust-ini v0.18.0
   Compiling natord v1.0.9
   Compiling dominant_color v0.3.0
   Compiling bytesize v1.2.0
   Compiling gifski v1.10.0
   Compiling hex v0.4.3
   Compiling sixel-rs v0.3.3
   Compiling webp v0.2.2
   Compiling image v0.24.5
   Compiling viuer v0.6.2
   Compiling menyoki v1.7.0 (/home/daru/menyoki-git/src/menyoki)
    Finished release [optimized] target(s) in 2m 41s
==> Starting check()...
   Compiling libc v0.2.139
   Compiling cfg-if v1.0.0
   Compiling autocfg v1.1.0
   Compiling scopeguard v1.1.0
   Compiling crossbeam-utils v0.8.15
   Compiling proc-macro2 v1.0.51
   Compiling quote v1.0.23
   Compiling unicode-ident v1.0.6
   Compiling once_cell v1.17.1
   Compiling version_check v0.9.4
   Compiling syn v1.0.109
   Compiling bitflags v1.3.2
   Compiling rayon-core v1.10.2
   Compiling bytemuck v1.13.1
   Compiling memoffset v0.8.0
   Compiling crossbeam-epoch v0.9.14
   Compiling num-traits v0.2.15
   Compiling ahash v0.7.6
   Compiling lock_api v0.4.9
   Compiling crc32fast v1.3.2
   Compiling adler v1.0.2
   Compiling miniz_oxide v0.6.2
   Compiling crossbeam-deque v0.8.3
   Compiling crossbeam-channel v0.5.7
   Compiling rgb v0.8.36
   Compiling weezl v0.1.7
   Compiling getrandom v0.2.8
   Compiling num_cpus v1.15.0
   Compiling jobserver v0.1.26
   Compiling log v0.4.17
   Compiling either v1.8.1
   Compiling flate2 v1.0.25
   Compiling cc v1.0.79
   Compiling hashbrown v0.12.3
   Compiling num-integer v0.1.45
   Compiling color_quant v1.1.0
   Compiling smallvec v1.10.0
   Compiling pkg-config v0.3.26
   Compiling futures-core v0.3.26
   Compiling signal-hook v0.3.15
   Compiling rayon v1.6.1
   Compiling lazy_static v1.4.0
   Compiling parking_lot_core v0.9.7
   Compiling io-lifetimes v1.0.5
   Compiling nanorand v0.7.0
   Compiling signal-hook-registry v1.4.1
   Compiling spin v0.9.8
   Compiling num-rational v0.4.1
   Compiling rustix v0.36.8
   Compiling futures-sink v0.3.26
   Compiling simd-adler32 v0.3.4
   Compiling libwebp-sys v0.4.2
   Compiling zune-inflate v0.2.50
   Compiling x11 v2.21.0
   Compiling fallible_collections v0.4.6
   Compiling mio v0.8.6
   Compiling threadpool v1.8.1
   Compiling atty v0.2.14
   Compiling imgref v1.9.4
   Compiling linux-raw-sys v0.1.4
   Compiling bit_field v0.10.2
   Compiling half v2.2.1
   Compiling lebe v0.5.2
   Compiling signal-hook-mio v0.2.3
   Compiling parking_lot v0.12.1
   Compiling device_query v1.1.2
   Compiling gif v0.12.0
   Compiling gif v0.11.4
   Compiling png v0.17.7
   Compiling noisy_float v0.2.0
   Compiling jpeg-decoder v0.3.0
   Compiling dirs-sys v0.3.7
   Compiling term_size v0.3.2
   Compiling thread_local v1.1.7
   Compiling scoped_threadpool v0.1.9
   Compiling dlv-list v0.3.0
   Compiling tiff v0.8.1
   Compiling thiserror v1.0.38
   Compiling fastrand v1.9.0
   Compiling byteorder v1.4.3
   Compiling static_assertions v1.1.0
   Compiling arrayvec v0.7.2
   Compiling unicode-width v0.1.10
   Compiling textwrap v0.11.0
   Compiling nix v0.26.2
   Compiling imagequant v4.1.0
   Compiling tempfile v3.4.0
   Compiling ordered-multimap v0.4.3
   Compiling dirs v4.0.0
   Compiling gif-dispose v4.0.0
   Compiling crossterm v0.25.0
   Compiling loop9 v0.1.3
   Compiling colored v2.0.0
   Compiling pin-project-internal v1.0.12
   Compiling thiserror-impl v1.0.38
   Compiling lodepng v3.7.2
   Compiling resize v0.7.4
   Compiling console v0.15.5
   Compiling ansi_colours v1.2.1
   Compiling time v0.1.45
   Compiling base64 v0.13.1
   Compiling iana-time-zone v0.1.53
   Compiling yansi v0.5.1
   Compiling strsim v0.8.0
   Compiling mutate_once v0.1.1
   Compiling diff v0.1.13
   Compiling termcolor v1.2.0
   Compiling ansi_term v0.12.1
   Compiling pin-project v1.0.12
   Compiling flume v0.10.14
   Compiling quick-error v2.0.1
   Compiling clap v2.34.0
   Compiling pretty_assertions v1.3.0
   Compiling kamadak-exif v0.5.5
   Compiling chrono v0.4.23
   Compiling ctrlc v3.2.5
   Compiling exr v1.5.3
   Compiling fern_colored v0.6.1
   Compiling shellexpand v3.1.0
   Compiling rust-ini v0.18.0
   Compiling gifski v1.10.0
   Compiling natord v1.0.9
   Compiling hex v0.4.3
   Compiling bytesize v1.2.0
   Compiling dominant_color v0.3.0
   Compiling webp v0.2.2
   Compiling image v0.24.5
   Compiling viuer v0.6.2
   Compiling menyoki v1.7.0 (/home/daru/menyoki-git/src/menyoki)
    Finished test [unoptimized + debuginfo] target(s) in 52.54s
     Running unittests src/main.rs (target/debug/deps/menyoki-817f376abe453510)

running 35 tests
test anim::tests::test_anim_mode ... ok
test analyze::settings::tests::test_time_zone ... ok
test anim::decoder::tests::test_anim_decoder ... ok
test apng::tests::test_apng_encoder ... ok
test anim::settings::tests::test_anim_settings ... ok
test analyze::settings::tests::test_analyze_settings ... ok
test args::matches::tests::test_matches ... FAILED
test anim::settings::tests::test_split_settings ... ok
test args::parser::tests::test_parser ... ok
test edit::settings::tests::test_edit_settings ... ok
test analyze::tests::test_analyze ... ok
test file::settings::tests::test_save_settings ... FAILED
test image::geometry::tests::test_geometry ... ok
test gif::encoder::tests::test_gif_encoder ... ok
test image::padding::tests::test_padding ... ok
test image::settings::tests::test_jpg_settings ... ok
test image::settings::tests::test_pnm_settings ... ok
test image::settings::tests::test_webp_settings ... ok
test image::settings::tests::test_png_settings ... ok
test image::tests::test_image ... ok
test record::settings::tests::test_record_settings ... FAILED
test gif::encoder::tests::test_gifski_encoder ... ok
test settings::tests::test_app_settings ... ok
test file::tests::test_file ... FAILED
test util::keys::tests::test_action_keys ... ok
test util::logger::tests::test_logger ... ok
test view::settings::tests::test_view_settings ... ok
test app::tests::test_app_image ... ok
                                      test args::tests::test_shell_completions ... ok
                                                                                     test util::comm
and:
:tests::test_command ... ok
                               test edit::tests::test_edit ... ok
                                                                 test record::fps::tests::test_fps .
.. o
k
     test app::tests::test_app_anim ... ok
                                          test record::tests::test_record ... ok
                                                                                test view::tests::te
st_v
iew has been running for over 60 seconds
test view::tests::test_view ... ok

failures:

---- args::matches::tests::test_matches stdout ----
thread 'args::matches::tests::test_matches' panicked at src/args/matches.rs:172:9:
assertion failed: `(left == right)`

Diff < left / right > :
<ArgMatches { args: ArgMatches { args: {}, subcommand: None, usage: None }, config: true, section: "
gene
ral" }
>ArgMatches { args: ArgMatches { args: {}, subcommand: None, usage: None }, config: false, section: 
"gen
eral" }


note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- file::settings::tests::test_save_settings stdout ----
thread 'file::settings::tests::test_save_settings' panicked at src/file/settings.rs:135:9:
assertion failed: save_settings.file.path.to_str().unwrap().contains("test_")

---- record::settings::tests::test_record_settings stdout ----
thread 'record::settings::tests::test_record_settings' panicked at src/record/settings.rs:427:9:
assertion failed: `(left == right)`

Diff < left / right > :
 Root(
<    Some(
<        Geometry {
<            x: 0,
<            y: 0,
<            width: 10,
<            height: 10,
<        },
<    ),
>    None,
 )



---- file::tests::test_file stdout ----
thread 'file::tests::test_file' panicked at src/file/mod.rs:150:13:
assertion failed: `(left == right)`

Diff < left / right > :
<Some(
<    Date(
<        "",
<    ),
<)
>None




failures:
    args::matches::tests::test_matches
    file::settings::tests::test_save_settings
    file::tests::test_file
    record::settings::tests::test_record_settings

test result: FAILED. 31 passed; 4 failed; 0 ignored; 0 measured; 0 filtered out; finished in 858.71s

error: test failed, to rerun pass `--bin menyoki`
==> ERROR: A failure occurred in check().
    Aborting...
```
</details>

**Comment by orhun** [comment]
You can skip the tests for this case. (`makepkg -si --nocheck`)

**Comment by Darukutsu** [comment]
Seems to work as expected, thanks.

**Comment by orhun** [comment]
Great! closing
